import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import GlobalProvider from "@/components/layout/GlovalProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "car audio expert",
  description: "Generated by create next app",
};

 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Toaster position="top-right" reverseOrder={false} />
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
